package com.example.e_commerce_iti.model.pojos.draftorder

data class DraftOrder(
    var applied_discount: AppliedDiscount?=null,
    var billing_address: BillingAddress?=null,
    var completed_at: String?=null,
    var created_at: String?=null,
    var currency: String?=null,
    var customer: Customer?=null,
    var email: String?=null,
    var id: Long?=null,
    var invoice_sent_at: String?=null,
    var invoice_url: String?=null,
    var line_items: List<LineItems>,
    var name: String?=null,
    var note: Any?=null,
    var note_attributes: List<NoteAttribute>?=null,
    var order_id: OrderId?=null,
    var payment_terms: PaymentTerms?=null,
    var shipping_address: ShippingAddress?=null,
    var shipping_line: ShippingLine?=null,
    var source_name: String?=null,
    var status: String?=null,
    var subtotal_price: String?=null,
    var tags: String?=null,
    var tax_exempt: Boolean?=null,
    var tax_exemptions: List<String>?=null,
    var tax_lines: List<TaxLineX>?=null,
    var taxes_included: Boolean?=null,
    var total_price: String?=null,
    var total_tax: String?=null,
    var updated_at: String?=null
)